### ISSUE TITLE
MN Adoc: All sections above 5 equal signs need to be encoded

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/sts2mn#12]
All sections above 5 equal signs need to be encoded specially:

e.g.
```adoc
====== My section
```

Should be
```
```adoc
[level=6]
===== My section
```

**Comment by Intelligent2013** [comment]
Fixed in [Release 1.1](https://github.com/metanorma/sts2mn/releases/download/v1.1/sts2mn-1.1.jar).
But if  ` ```adoc` is a typo in a sample, please inform me, I'll remove it.
