### ISSUE TITLE
Adoc: Bad links to terms

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/sts2mn#24]
Source: https://github.com/metanorma/mn-samples-bsi/issues/2
In adoc there is a link
```
activities of <<term_3.19,organizations>>.
```
but there isn't `[[term_3.19]]` in the text.

**Comment by Intelligent2013** [comment]
Done.
Additional task: add links in https://github.com/metanorma/bs-202000/tree/master/sources.

**Comment by ronaldtse** [comment]
@Intelligent2013 anything I need to do here?

**Comment by Intelligent2013** [comment]
@ronaldtse no, thank you. I'm updating terms links in adoc. Adoc's were generated without links to terms (STS `named-content` tag), therefore I merge changes into bs-200200 with fixed issues. I can't just overwrite it.

**Comment by Intelligent2013** [comment]
Done.

**Comment by Intelligent2013** [comment]
@ronaldtse when you have a chance, please take a look at https://github.com/metanorma/bs-202000/pull/5. I've added term's references and add bibdata fields.
