### ISSUE TITLE
Generate term references term:[xxx]

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/sts2mn#26]
Source: https://github.com/metanorma/mn-samples-bsi/issues/2
Source: https://github.com/metanorma/bs-202000/pull/8#pullrequestreview-663757596

Instead of
`<<term-organization,organization>>`
generate
`term:[xxx]`
or
~`term:[original,rendered]`~ `term:[rendered,original]`
in case  if the term referenced and rendered are different.

**Comment by Intelligent2013** [comment]
<xref target="term-organization">organization</xref>

**Comment by Intelligent2013** [comment]
@ronaldtse if change to `term:[..]` format, then we get differences in resulted and original PDFs. And  `term:[organization,organizations]` doesn't working properly.

original PDF:
![image](https://user-images.githubusercontent.com/5559926/118940675-9ea87480-b959-11eb-89d8-4c1c6d05c97b.png)

adoc: `<<term-organization,organization>>`
xml: `<xref target="term-organization">organization</xref>`
resulted pdf: 
![image](https://user-images.githubusercontent.com/5559926/118940839-cc8db900-b959-11eb-8caf-a65d6db5834a.png)


adoc: term:[organization]
xml: `<em>organization</em> (<xref target="term-organization"><strong>3.19</strong></xref>)`
resulted pdf: 
![image](https://user-images.githubusercontent.com/5559926/118940885-d9121180-b959-11eb-9419-81cc63f5f82b.png)


adoc: `term:[organization,organizations]`
xml: `(<strong>term &#8220;organization&#8221; not resolved</strong>)`
resulted pdf: 
![image](https://user-images.githubusercontent.com/5559926/118940925-e29b7980-b959-11eb-94eb-4499d65e4e25.png)

**Comment by ronaldtse** [comment]
The extra parenthesis is a bug: https://github.com/metanorma/metanorma-standoc/issues/468

The second issue is maybe the front/back terms need to be switched (my mistake).

**Comment by Intelligent2013** [comment]
@ronaldtse yes, after terms switching is works ok. thank you!
adoc; `term:[organizations,organization]`
xml: `<em>organizations</em> (<xref target="term-organization"><strong>3.19</strong></xref>)`
resulted pdf:
![image](https://user-images.githubusercontent.com/5559926/118952745-dc5eca80-b964-11eb-9083-31dd46b0d29e.png)

**Comment by Intelligent2013** [comment]
Done.
