### ISSUE TITLE
U+FEFF appears in multiple parts of a converted document

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/sts2mn#28]
Should be all removed.

<img width="608" alt="Screenshot 2021-05-21 at 1 14 04 AM" src="https://user-images.githubusercontent.com/11865/119021300-dbb04d80-b9d1-11eb-8d5c-65a858a9d8b8.png">

<img width="616" alt="image" src="https://user-images.githubusercontent.com/11865/119021235-c509f680-b9d1-11eb-81d4-58d0a5cb6ed6.png">

**Comment by Intelligent2013** [comment]
@ronaldtse this document (BS 44001) was created manually, without of using sts2mn tool.
I've created adocs with sts2mn and there aren't U+FEFF characters there.

**Comment by Intelligent2013** [comment]
I've removed them from repo.

**Comment by ronaldtse** [comment]
Oh! Sorry about that. Thanks for fixing the document.
