### ISSUE TITLE
BSI document types should be reflected

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/sts2mn#30]
BS: British Standard
PD: Published Documents
PAS: publicly accessible standard

**Comment by Intelligent2013** [comment]
Source: https://github.com/metanorma/mn-samples-bsi/issues/2
To do:

### PAS:
- Source STS XML:
`/standard/front/nat-meta/std-ident/originator` = "PAS" and
`/standard/front/nat-meta/std-ident/doc-type` = "Publicly Available Specification" or "Standard"
_Simplified rule_: `/standard/front/nat-meta/std-ident/originator` starts with "PAS"

- Destination MN xml: `bibdata/ext/doctype` = "publicly-available-specification"
- Destination  MN adoc: `:doctype: publicly-available-specification`
(Based on: https://github.com/metanorma/metanorma-bsi/issues/16)

### PD:

- Source STS XML:
`/standard/front/nat-meta/std-ident/originator` = "PD ISO" and 
`/standard/front/nat-meta/std-ident/doc-type` = "Published Document"
_Simplified rule_:
`/standard/front/nat-meta/std-ident/originator` start with "PD" and 
`/standard/front/nat-meta/std-ident/doc-type` lower cased = "published document"

- Destination MN xml: `bibdata/ext/doctype` = "published-document"
- Destination  MN adoc: `:doctype: published-document`


### BS:  
- Source STS XML:
`/standard/front/nat-meta/std-ident/originator` = "BS", or  "BS ISO", "BS EN", "BS EN ISO" and 
`/standard/front/nat-meta/std-ident/doc-type` = "Standard"
_Simplified rule_:
`/standard/front/nat-meta/std-ident/originator` start with "BS" and 
`/standard/front/nat-meta/std-ident/doc-type` lower-cased = "standard"

- Destination MN xml `bibdata/ext/doctype` = "standard"
- Destination MN adoc `:doctype: standard`

**Comment by Intelligent2013** [comment]
Done.
