### ISSUE TITLE
STS XML xxx-meta elements processing

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/sts2mn#31]
Source: https://github.com/metanorma/metanorma-standoc/issues/458
https://github.com/metanorma/mn-samples-bsi/issues/2

> The rules are as following:
>
> * Only make a distinction between `nat-meta`, `reg-meta`, `iso-meta` if `//bibdata/relation[@type = 'adopted-from']` exists. If not, then all information from `//bibdata` goes to the default metadata container (which I assume is `std-doc-meta`).
> * If `//bibdata/relation[@type = 'adopted-from']` exists, `//bibdata` (ignoring all instances of `.//relation[@type = 'adopted-from']/bibitem`) is nat-meta: it is the national standards body's metadata (BSI being a national body)
> * If `//bibdata//relation[@type = 'adopted-from']/bibitem/contributor[role/@type = 'publisher']/organization[abbreviation = 'xxx']` exists, where xxx = ISO or IEC, then `//bibdata//relation[@type = 'adopted-from']/bibitem[contributor[role/@type = 'publisher']/organization[abbreviation = 'xxx']]` goes to iso-meta: it is the ISO (or IEC) metadata of a source document that this document is derived from (adopted from).
> * If `//bibdata//relation[@type = 'adopted-from']/bibitem/contributor[role/@type = 'publisher']/organization[abbreviation = 'xxx']` exists, where xxx = CEN or CENELEC, then `//bibdata//relation[@type = 'adopted-from']/bibitem[contributor[role/@type = 'publisher']/organization[abbreviation = 'xxx']]` goes to reg-meta: it is the metadata of a regional organisation source document that this document is derived from (adopted from). (CEN is the European region counterpart to ISO, CENELEC the European region counterpart to IEC.)
> * If BSI ever adopts a standard from a body other than the four I have named, `std-meta` should be used for that body's metadata instead: the tag `iso-meta` is only intended for ISO-like metadata, and `reg-meta` is reserved for regional affiliates of ISO.
> * It is possible that we will have relation instances featuring the type `derived-from` instead of `adopted-from`. However, `adopted-from` is what the current gem has permitted.

**Comment by Intelligent2013** [comment]
sts2mn should process these cases:
- if there is `nat-meta`, then 
  -  `nat-meta` goes to `bibdata`
  - `iso-meta` goes to `bibdata/relation[@type = 'adopted-from']/bibitem/contributor[role/@type = 'publisher']/organization[abbreviation = 'xxx']` (xxx = ISO or IEC)
  - `reg-meta` goes to `bibdata/relation[@type = 'adopted-from']/bibitem/contributor[role/@type = 'publisher']/organization[abbreviation = 'xxx']` (xxx = CEN or CENELEC)
  - `std-meta` goes to`bibdata/relation[@type = 'adopted-from']/bibitem/contributor[role/@type = 'publisher']/organization[abbreviation = 'xxx']` (xxx != ISO, IEC, CEN, CENELEC)

- if there isn't `nat-meta`, then
  - `iso-meta `goes to `bibdata`
  - `reg-meta` goes to `bibdata/relation[@type = 'adopted-from']/bibitem/contributor[role/@type = 'publisher']/organization[abbreviation = 'xxx']` (xxx = CEN or CENELEC)
  - `std-meta` goes to`bibdata/relation[@type = 'adopted-from']/bibitem/contributor[role/@type = 'publisher']/organization[abbreviation = 'xxx']` (xxx != ISO, IEC, CEN, CENELEC)

**Comment by Intelligent2013** [comment]
@opoudjis could you point me, how should look adoc markup for `relation[@type = 'adopted-from']/bibitem`? May be I'm in a hurry and metanorma doesn't support it yet...

**Comment by opoudjis** [comment]
The adopted-from header is not supported generically, but in the specific instance of BSI, it is supported as a document attribute:

`:adopted-from: ISO 639-2`

**Comment by Intelligent2013** [comment]
Further changes in: https://github.com/metanorma/mnconvert/issues/5
Closing.
