### ISSUE TITLE
Re-generate adocs when sts2mn updated

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/sts2mn#55]
Re-generate adocs for each xml in https://github.com/metanorma/mn-samples-bsi/reference-docs after each update.

**Comment by Intelligent2013** [comment]
to do:
1. xslt https://github.com/metanorma/metanorma-bsi/blob/main/lib/isodoc/bsi/bsi.international-standard.xsl should be download in bsi_update task, not by user-side
2. command `git push origin master` raises an error:
```
git push origin master
error: src refspec master does not match any
error: failed to push some refs to 'https://github.com/metanorma/mn-samples-bsi'
make: *** [bsi_update] Error 1
Makefile:20: recipe for target 'bsi_update' failed
```

**Comment by Intelligent2013** [comment]
Start of log:
```
git add sources.sts2mn
git commit -a -m "adoc auto-updated"
[detached HEAD 4033b40] adoc auto-updated
 476 files changed, 55838 insertions(+)
```

**Comment by Intelligent2013** [comment]
Git push moved to yml from makefile:
```
fatal: You are not currently on a branch.
[detached HEAD 98f8f10] adoc auto-updated
To push the history leading to the current (detached HEAD)
 1 file changed, 789 insertions(+), 6857 deletions(-)
 rewrite sources.sts2mn/bsi.international-standard.xsl (97%)
state now, use
HEAD detached from 1676570
nothing to commit, working tree clean

    git push origin HEAD:<name-of-remote-branch>
```

**Comment by ronaldtse** [comment]
There are two issues:
- the target repo is a private one, so we need a suitable token to push
- If we are pushing to an existing branch we need to add the “--force” parameter

**Comment by Intelligent2013** [comment]
@ronaldtse thank you! But it seems issue in missed `ref` (https://github.com/actions/checkout):
```
- uses: actions/checkout@v2
          ref: test-auto-generate
```

**Comment by ronaldtse** [comment]
Thanks @Intelligent2013 !

**Comment by Intelligent2013** [comment]
After push from workflow, github run cyclic workflows (https://github.com/metanorma/mn-samples-bsi/actions)
![image](https://user-images.githubusercontent.com/5559926/120591571-0a540c80-c445-11eb-8f16-a2cef5e440d8.png)
Will investigate...

**Comment by Intelligent2013** [comment]
Solved. Added `[skip actions]` in commit message.
Found here: https://github.blog/changelog/2021-02-08-github-actions-skip-pull-request-and-push-workflows-with-skip-ci/.

Last remaining task - download bsi xslt from private metanorma-bsi repo.

**Comment by Intelligent2013** [comment]
All done.
- sts2mn notifying mn-samples-bsi
- mn-sample-bsi re-generate adocs with latest sts2mn xsl
