### ISSUE TITLE
sts2mn doesn't notify sts2mn-ruby

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/sts2mn#56]
Latest release sts2mn - 14 days ago.
Latest release sts2mn-ruby - 11 month ago.

**Comment by CAMOBAP** [comment]
Hmm, I have compared `mn2pdf -> mn2pdf-ruby` `mn2sts -> mn2sts-ruby`:
 - `mn2pdf` use `PAT_TOKEN` for some reason while `mn2sts` uses `METANORMA_CI_PAT_TOKEN`

@ronaldtse could you please confirm that `METANORMA_CI_PAT_TOKEN` include all 4 repos:
 - `mn2pdf`
 - `mn2pdf-ruby`
 - `mn2sts`
 - `mn2sts-ruby`

**Comment by Intelligent2013** [comment]
I've made some changes here:
https://github.com/metanorma/sts2mn-ruby/commit/12b9507dcd88942e6c751a36a97cd5daf9c380e9
I'll try to release sts2mn now and let's see what happened...

**Comment by ronaldtse** [comment]
`METANORMA_CI_PAT_TOKEN` is available to all public repositories.

**Comment by ronaldtse** [comment]
@CAMOBAP let's remove the PAT_TOKEN from mn2pdf, probably legacy

**Comment by ronaldtse** [comment]
mn2sts does not have the "Deploy to Maven" step enabled though:
https://github.com/metanorma/mn2sts/blob/82c5b756b4d2354f5a091eb6526d7d853a0e71df/.github/workflows/release.yml#L66-L72

This is the part using PAT_TOKEN and PAT_USERNAME.

**Comment by Intelligent2013** [comment]
@CAMOBAP 
mn2sts-ruby - ok (https://github.com/metanorma/mn2sts-ruby/runs/2651230505?check_suite_focus=true):
![image](https://user-images.githubusercontent.com/5559926/120464736-ee4d5e00-c3a5-11eb-8b04-a5f389b8c96e.png)

sts2mn-ruby - not ok (https://github.com/metanorma/sts2mn-ruby/runs/2726682290?check_suite_focus=true):
![image](https://user-images.githubusercontent.com/5559926/120464797-fe653d80-c3a5-11eb-85c2-5b4a76113964.png)

`"Ignoring mn2sts. Version file ? not found. Aborting."` Why `mn2sts` for `sts2mn-ruby` repo? It's puzzle for me...

**Comment by Intelligent2013** [comment]
mn2sts.gemspec file!

**Comment by Intelligent2013** [comment]
Further issues: https://github.com/metanorma/sts2mn-ruby/runs/2726895911?check_suite_focus=true
```
Failures:

  1) Sts2mn converts STS to MN adoc in specified location
     Failure/Error: expect(File.exist?(File.join(dir, 'body', 'body-en.adoc'))).to be true

       expected true
            got false
     # ./spec/sts2mn_spec.rb:40:in `block in convert_to_format'
     # ./spec/sts2mn_spec.rb:18:in `convert_to_format'
     # ./spec/sts2mn_spec.rb:13:in `block (3 levels) in <top (required)>'

Finished in 4.41 seconds (files took 0.10938 seconds to load)
5 examples, 1 failure

Failed examples:

rspec './spec/sts2mn_spec.rb[1:2]' # Sts2mn converts STS to MN adoc in specified location

/opt/hostedtoolcache/Ruby/2.6.7/x64/bin/ruby -I/opt/hostedtoolcache/Ruby/2.6.7/x64/lib/ruby/gems/2.6.0/gems/rspec-core-3.10.1/lib:/opt/hostedtoolcache/Ruby/2.6.7/x64/lib/ruby/gems/2.6.0/gems/rspec-support-3.10.2/lib /opt/hostedtoolcache/Ruby/2.6.7/x64/lib/ruby/gems/2.6.0/gems/rspec-core-3.10.1/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb failed
```

**Comment by Intelligent2013** [comment]
Non-correct expectation in `expect(File.exist?(File.join(dir, 'body', 'body-en.adoc'))).to be true`. Fixing...

**Comment by CAMOBAP** [comment]
I see the original issue, fix in progress

oops, looks like already fixed by @Intelligent2013 ,thanks

**Comment by CAMOBAP** [comment]
@Intelligent2013 I saw that 1.3 tag was removed from sts2mn, will you push it again?

**Comment by Intelligent2013** [comment]
> 
> 
> @Intelligent2013 I saw that 1.3 tag was removed from sts2mn, will you push it again?

Yes, because I don't know how to run release-tag.yml manually...

**Comment by CAMOBAP** [comment]
@Intelligent2013 to be on the same page, will you push it back? If some collision happens on sts2mn-ruby I will release it manually

**Comment by Intelligent2013** [comment]
@CAMOBAP could you take a look, why
```ruby
expect(File.exist?(File.join(dir, 'body', 'body-en.adoc'))).to be true
```
ok for regular workflows (https://github.com/metanorma/sts2mn-ruby/runs/2727334676) and failed for release-tag.yml (https://github.com/metanorma/sts2mn-ruby/runs/2726895911?check_suite_focus=true) ?

**Comment by CAMOBAP** [comment]
@Intelligent2013 yep on it

**Comment by CAMOBAP** [comment]
Ready for review

**Comment by Intelligent2013** [comment]
> Ready for review

Approved. But I didn't understand how changes in tests can solve the issue... Should I try to push a release?

**Comment by CAMOBAP** [comment]
@Intelligent2013 oh my bad I forgot to uncomment getAbsoluteFile, I will restart release

**Comment by CAMOBAP** [comment]
@Intelligent2013 could you please check https://github.com/metanorma/sts2mn/commit/a93f5bad1fa44d06624fd7de935935e709b9f441

But this isn't the whole story, I have a question about https://github.com/metanorma/sts2mn/commit/8f7e6a121ce8927c4ac2c8d7ab75cbbd2e413fae is this some temporal decision or not?

Looks like we need to remove this assert https://github.com/metanorma/sts2mn-ruby/blob/master/spec/sts2mn_spec.rb#L39-L43

**Comment by Intelligent2013** [comment]
@CAMOBAP 

> @Intelligent2013 could you please check [a93f5ba](https://github.com/metanorma/sts2mn/commit/a93f5bad1fa44d06624fd7de935935e709b9f441)

It seems working ok as earlier.

> But this isn't the whole story, I have a question about [8f7e6a1](https://github.com/metanorma/sts2mn/commit/8f7e6a121ce8927c4ac2c8d7ab75cbbd2e413fae) is this some temporal decision or not?

no, this fragment will be deleted, obsoleted.

**Comment by CAMOBAP** [comment]
> It seems working ok as earlier.

Previous it incorrectly handled `--output text.adoc` because `getParent()` returned null

> no, this fragment will be deleted, obsoleted.

Thanks

**Comment by CAMOBAP** [comment]
@ronaldtse could you please help 
> You do not have permission to push to this gem. Ask an owner to add you with: gem owner sts2mn --add metanorma@ribose.com

**Comment by ronaldtse** [comment]
@CAMOBAP added! Didn't know that the whole time metanorma-ci couldn't release the gem...
