### ISSUE TITLE
bolded text without spacing on both sides require doubling of `*` to `**`

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/sts2mn#79]
From BS ISO 44001:

<img width="633" alt="Screenshot 2021-06-25 at 11 40 38 AM" src="https://user-images.githubusercontent.com/11865/123366105-32e5a700-d5aa-11eb-8a66-7fc7009d625c.png">

**Comment by Intelligent2013** [comment]
Fixed:
![image](https://user-images.githubusercontent.com/5559926/123541276-55172a80-d74c-11eb-9319-f1db8841f7cb.png)

**Comment by ronaldtse** [comment]
Thanks @Intelligent2013 !
